// src/components/Complaint.js
import React, { useState } from 'react';
import styled from 'styled-components';
import { useNavigate } from 'react-router-dom';

const Container = styled.div`
  background-color: #1a1b2e;
  min-height: 100vh;
  padding: 2rem;
`;

const Title = styled.h1`
  color: #4169E1;
  text-align: center;
  font-size: 2rem;
  margin-bottom: 2rem;
`;

const ComplaintCard = styled.div`
  background-color: white;
  border-radius: 15px;
  padding: 1.5rem;
  margin: 1rem auto;
  max-width: 800px;
  position: relative;
`;

const UserInfo = styled.div`
  display: flex;
  align-items: center;
  margin-bottom: 1rem;
`;

const Avatar = styled.div`
  width: 40px;
  height: 40px;
  background-color: #ddd;
  border-radius: 50%;
  margin-right: 1rem;
`;

const UserDetails = styled.div`
  color: black;
  
  .username {
    font-weight: bold;
  }
  
  .location {
    font-size: 0.9rem;
    color: #666;
    
    span {
      color: #ff0000;
    }
  }
`;

const ComplaintText = styled.p`
  color: black;
  margin-bottom: 1rem;
  
  .warning {
    color: #ff0000;
    font-weight: bold;
  }
`;

const ButtonGroup = styled.div`
  position: absolute;
  right: 1rem;
  top: 1rem;
  display: flex;
  gap: 0.5rem;
`;

const ActionButton = styled.button`
  padding: 0.5rem 1rem;
  border-radius: 5px;
  border: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 0.3rem;
  
  &.verify {
    background-color: #e7f7e7;
    color: #2e7d32;
  }
  
  &.remove {
    background-color: #ffebee;
    color: #c62828;
  }
`;

const AddButton = styled.button`
  background-color: #4169E1;
  color: white;
  border: none;
  padding: 0.8rem 3rem;
  border-radius: 10px;
  font-size: 1.1rem;
  cursor: pointer;
  display: block;
  margin: 2rem auto;
  
  &:hover {
    background-color: #3151b0;
  }
`;

function Complaint() {
  const navigate = useNavigate();
  const [complaints] = useState([
    {
      id: 1,
      user: 'Tan',
      location: '7-11',
      time: 'added a complaint 2 hours ago',
      content: 'Warning! I am writing to formally express my concern regarding the loud noise generated by the jackhammering activity occurring at the 7-11. The noise levels have been disruptive to the surrounding community and have significantly impacted our daily routines.'
    },
    {
      id: 2,
      user: 'Pai',
      location: '7-11',
      time: 'added a complaint 2 hours ago',
      content: 'Jack hammer disruption! I am writing to formally address the excessive noise generated by jackhammer activity at the 7-11. The persistent noise has created a significant disturbance for residents in the vicinity.'
    },
    {
      id: 3,
      user: 'Win',
      location: '7-11',
      time: 'added a complaint 2 hours ago',
      content: `Very loud! Hope this message finds you well. I wanted to bring up the loud noise from the jackhammer at the 7-11 that's in effect. It's been quite disruptive, especially during the early morning hours and its making it hard for folks in the area to go about their day.`
    }
  ]);

  const handleVerify = (id) => {
    console.log('Verify complaint:', id);
  };

  const handleRemove = (id) => {
    console.log('Remove complaint:', id);
  };

  const handleAddComplaint = () => {
    navigate('/complaints/add');
  };

  return (
    <Container>
      <Title>Complaint</Title>
      
      {complaints.map(complaint => (
        <ComplaintCard key={complaint.id}>
          <UserInfo>
            <Avatar />
            <UserDetails>
              <div className="username">{complaint.user}</div>
              <div className="location">
                Location: <span>{complaint.location}</span>
              </div>
            </UserDetails>
          </UserInfo>
          
          <ComplaintText>
            {complaint.content}
          </ComplaintText>
          
          
        </ComplaintCard>
      ))}

      <AddButton onClick={handleAddComplaint}>
        Add complaint
      </AddButton>
    </Container>
  );
}

export default Complaint;